include:
  - board: xiao_ble//zmk
    shield: totem_left
  - board: xiao_ble//zmk
    shield: totem_right
# there is no settingsreset (needed) for the XIAO

  # - board: eyelash_corne_left
  #   shield: nice_view
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  #   artifact-name: eyelash_corne_left_no_dongle_studio

  # - board: eyelash_corne_right
  #   shield: nice_view
  #   artifact-name: eyelash_corne_right_no_dongle

  # # Dongle build: nice!nano dongle is central, both halves are peripherals.
  - board: nice_nano//zmk
    shield: totem_dongle dongle_display
    snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: totem_dongle

  # - board: eyelash_corne_peripheral_left
  #   shield: nice_view_adapter nice_view_custom
  #   artifact-name: eyelash_corne_left_for_dongle

  # - board: eyelash_corne_peripheral_right
  #   shield: nice_view_adapter nice_view_custom 
  #   artifact-name: eyelash_corne_right_for_dongle

  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: settings_reset_nice_nano_v2
